#!/usr/bin/env sh

yabai -m config                           \
  bottom_padding              10          \
  left_padding                10          \
  right_padding               10          \
  top_padding                 10          \
  window_gap                  10          \
  layout                      bsp         \
  split_ratio                 0.5         \
  split_type                  auto        \
  window_origin_display       focused     \
  window_border               on          \
  window_border_width         1           \
  window_border_radius        11          \
  window_border_blur          off         \
  window_border_hidpi         off         \
  window_zoom_persist         true        \
  active_window_border_color  0xff9697d4  \
  normal_window_border_color  0x7f353535  \
  insert_feedback_color       0xff9697d4

yabai -m rule --add app!="^(Code|Brave Browser|Firefox|kitty|Safari)$" manage=off
yabai -m rule --add app="^Firefox$" title="^Library$" manage=off
yabai -m rule --add app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advanced)$" manage=off
