Hyper:bind({}, "a", function() hs.application.launchOrFocus("kitty") end)
Hyper:bind({}, "c", function() hs.application.launchOrFocus("Calendar") end)
Hyper:bind({}, "d", function() hs.application.launchOrFocus("Spotify") end)
Hyper:bind({}, "e", function() hs.application.launchOrFocus("Mail") end)
Hyper:bind({}, "f", function() hs.application.launchOrFocus("Finder") end)
Hyper:bind({}, "g", function() hs.application.launchOrFocus("System Preferences") end)
Hyper:bind({}, "q", function() hs.application.launchOrFocus("Signal") end)
Hyper:bind({}, "r", function() hs.application.launchOrFocus("Notes") end)
Hyper:bind({}, "s", function() hs.application.launchOrFocus("Safari") end)
Hyper:bind({}, "t", function() hs.application.launchOrFocus("Calculator") end)
Hyper:bind({}, "v", function() hs.application.launchOrFocus("Firefox") end)
Hyper:bind({}, "w", function() hs.application.launchOrFocus("WhatsApp") end)
Hyper:bind({}, "x", function() hs.application.launchOrFocus("Launchpad") end)
Hyper:bind({}, "z", function() hs.application.launchOrFocus("Activity Monitor") end)

Hyper:bind({ "cmd" }, "f", function() hs.application.launchOrFocus("Visual Studio Code") end)
Hyper:bind({ "cmd" }, "g", function() hs.application.launchOrFocus("App Store") end)
Hyper:bind({ "cmd" }, "r", function() hs.application.launchOrFocus("Reminders") end)
Hyper:bind({ "cmd" }, "s", function() hs.application.launchOrFocus("Brave Browser") end)

Hyper:bind({ "cmd", "ctrl" }, "1", function() hs.osascript.applescriptFromFile("scripts/monitor1.applescript") end)
Hyper:bind({ "cmd", "ctrl" }, "2", function() hs.osascript.applescriptFromFile("scripts/monitor2.applescript") end)
Hyper:bind({ "cmd", "ctrl" }, "3", function() hs.osascript.applescriptFromFile("scripts/monitor3.applescript") end)

Hyper:bind({ "cmd", "shift" }, "r", function() hs.reload() end)
